datasets:
  - sift-128-euclidean

index_params:
  - index_type: HNSW
    index_args:
      R: 48
      L: 200

rebuild: false
build_quant: SQ8U
search_quants:
  - SQ4U
refine_quant: FP16
topks:
  - 100
efs:
  - 100
  - 200
  - 300
runs: 3
concurrency:
  - 1
  - 2
  - 4
  - 8
  - 16
