name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff
      - name: Check C++ code format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
          clang-format --dry-run --Werror $(find glass -name "*.hpp")
      - name: Check Python code format
        run: |
          black --check .
          ruff check .

  build_and_test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Build project
      run: pip install -e "python"

    - name: Test project
      run: pytest "python"
